# Generated by Django 2.0.1 on 2018-02-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField(max_length=7)),
                ('recommend1', models.PositiveIntegerField(null=True)),
                ('recommend2', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
